apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort                    # Minikube cannot use LoadBalancer
  selector:
    app: auth
  ports:
  - port: 5000                      # Service port
    targetPort: 5000                # Container port
    nodePort: 30001                 # NodePort to access externally

